# plain text configuration object for the chart
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ (printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_")) | trunc 63 }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if (and .Values.config.enabled (not .Values.config.isFile)) }}
  {{- range $key, $val := .Values.config.data }}
  {{ $key }}: !!str {{ $val }}
  {{- end }}
  {{- if .Values.global.config }}
    {{- range $key, $val := .Values.global.config.data }}
  {{ $key }}: !!str {{ $val }}
    {{- end }}
  {{- end }}
{{- else if (and .Values.config.enabled .Values.config.isFile) }}
  {{ .Values.config.filename }}: |-
    {{- template "mergeConfigData" .Values }}
{{- else }}
  none: ""
{{- end }}
