apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ (printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_")) | trunc 63 }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if (and .Values.secrets.enabled (not .Values.secrets.isFile)) }}
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: !!str {{ b64enc $val | quote }}
  {{- end }}
  {{- if .Values.global.secrets }}
    {{- range $key, $val := .Values.global.secrets.data }}
  {{ $key }}: !!str {{ b64enc $val | quote }}
    {{- end }}
  {{- end }}
{{- else if (and .Values.secrets.enabled .Values.secrets.isFile) }}
  {{ .Values.secrets.filename }}: {{ toJson .Values.secrets.data }}
  {{ template "mergeSecretData" .Values }}
{{- else }}
  none: ""
{{- end }}
